name = "elec"
compatibility_date = "2025-09-15"
upload_source_maps = true
workers_dev = false

[observability]
enabled = true

[assets]
directory = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "nakiri-elec"
database_id = "5c764fbf-4212-4c70-8ad4-8dfb59194545"

[triggers]
crons = ["0 * * * *"]
