name = "elec"
compatibility_date = "2025-09-15"
upload_source_maps = true
workers_dev = false

[observability]
enabled = true

[assets]
# 根据您的构建日志，静态资源位于 dist/client 目录中
directory = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "elec"
database_id = "53d81a00-e326-4bac-8940-8b9020db85d9"

[triggers]
crons = ["0 * * * *"]
