name = "elec"
compatibility_date = "2025-09-15"
upload_source_maps = true
workers_dev = false

[observability]
enabled = true

[assets]
directory = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "nakiri-elec"
database_id = "8c120f99-a615-464e-a916-60bd9a89507c"

[triggers]
crons = ["0 * * * *"]
