name = "nakiri-elec"
compatibility_date = "2025-09-15"
upload_source_maps = true
workers_dev = false

[observability]
enabled = true

[assets]
directory = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "elec"
database_id = "9fbd4186-450b-45d8-bcb7-a7fb060e8911"

[triggers]
crons = ["0 * * * *"]
