name = "nakiri-elec"
main = "workers/index.ts"
compatibility_date = "2025-09-15"
upload_source_maps = true
workers_dev = false

[observability]
enabled = true

[assets]
directory = "dist"

[[d1_databases]]
binding = "DB"
database_name = "elec"
database_id = "2f539503-5e28-44bd-a4ca-29129746f9a0"

[triggers]
crons = ["0 * * * *"]
